# v1.1 - это версия конфига, обновите, если на сервере используется старая версия

telegram:
  token: "BOT_TOKEN" # Возьмите его в BotFather
  chat-id: "CHAT_ID" # Можно добавить бота в группу "@group_link" или писать лично в сообщения админу "123456"

message:
  telegram: "Игрок {player} зашёл на сервер" # {player} - никнейм зашедшего игрока
  server: "📢 Наш Telegram: " # выводится при подключении каждого игрока
  link: "https://t.me/link" # Если оставить поле пустым "", то ссылки выводиться не будет