# v1.2 - это версия конфига, обновите, если на сервере используется старая версия

telegram:
  token: "BOT_TOKEN" # Возьмите его в BotFather
  chat-id: "@group_link" # Можно добавить бота в группу "@group_link" или писать лично в сообщения админу "123456"

message:
  send-join: "true"
  join: "{player} присоединился к игре" # {player} - никнейм зашедшего игрока
  send-quit: "true"
  quit: "{player} покинул игру" # {player} - никнейм зашедшего игрока
  send-start: "true"
  start: "Сервер был запущен"
  send-disable: "true"
  disable: "Сервер был выключен"
  server: "📢 Наш Telegram: " # выводится при подключении каждого игрока
  link: "https://t.me/link" # Если оставить поле пустым "", то ссылки выводиться не будет